### ISSUE TITLE
Issues in running Healey & Leifeld 2018 replication code

### ISSUE THREAD

**Issue by charlesk1** [leifeld/btergm#14]
Hi Philip,

I had an error that I couldn't solve at this point of the code:

# H1: network embeddedness

# compute co-occurrence of coalition membership among coalition members
cpp.comember.strong <- cxxfunction(signature(mat = "matrix"), plugin = "Rcpp", 
    body = '
  IntegerMatrix mem = as<IntegerMatrix>(mat);
  int rows = mem.nrow();
  int cols = mem.ncol();
  Rcpp::NumericMatrix comemb = NumericMatrix(rows, cols);
  int realized;
  int possible;
  for (int i = 0; i < cols; i++) {
    for (int j = 0; j < rows; j++) {
      realized = 0;
      possible = 0;
      for (int k = 0; k < rows; k++) {
        for (int l = 0; l < cols; l++) {
          if (j != k && i != l && mem(j, i) == 1 && mem(k, i) == 1) {
            possible++;
            if (mem(k, l) == 1 && mem(j, l) == 1) {
              realized++;
            }
          }
        }
      }
      //std::cout << i << " " << j << " " << realized << " " << possible << "\\n";
      if (possible == 0.0) {
        comemb(j, i) = 0.0;
      } else {
        comemb(j, i) = double(realized) / double(possible);
      }
    }
  }
  return(wrap(comemb));
')

Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! Warning message:
In system(cmd) : 'make' not found
In addition: Warning message:
In system(cmd, intern = !verbose) :
  running command 'C:/PROGRA~1/R/R-36~1.0/bin/x64/R CMD SHLIB file1ee0752e18c4.cpp 2> file1ee0752e18c4.cpp.err.txt' had status 1

**Comment by leifeld** [comment]
Seems like the `make` command doesn't work on your system. Here are some ideas you could try:
 - Make sure the `Rcpp` package works on your system. E.g., try the minimal examples from [here](http://adv-r.had.co.nz/Rcpp.html). If that generates a problem, you should look for a way to install `Rcpp` properly.
- Make sure you have a C++ compiler installed on your system, e.g., G++. If you are using a Mac, it may be necessary to install `XCode`, which essentially provides these things.
- Go to the command line (the system terminal, not R) and type in `make` to see if you have a C++ compiler installed.
My best guess is that `Rcpp` doesn't work properly on your system. Perhaps you'll need to re-install the package or so.

**Comment by charlesk1** [comment]
Thanks!

De: Philip Leifeld <notifications@github.com>
Enviada em: segunda-feira, 1 de julho de 2019 11:09
Para: leifeld/btergm <btergm@noreply.github.com>
Cc: Charles Kirschbaum <CharlesK1@insper.edu.br>; Author <author@noreply.github.com>
Assunto: Re: [leifeld/btergm] Issues in running Healey & Leifeld 2018 replication code (#14)


Seems like the make command doesn't work on your system. Here are some ideas you could try:

  *   Make sure the Rcpp package works on your system. E.g., try the minimal examples from here<http://adv-r.had.co.nz/Rcpp.html>. If that generates a problem, you should look for a way to install Rcpp properly.
  *   Make sure you have a C++ compiler installed on your system, e.g., G++. If you are using a Mac, it may be necessary to install XCode, which essentially provides these things.
  *   Go to the command line (the system terminal, not R) and type in make to see if you have a C++ compiler installed.
My best guess is that Rcpp doesn't work properly on your system. Perhaps you'll need to re-install the package or so.

**Comment by leifeld** [comment]
You're welcome. I'll close this for now. But feel free to re-open if there are any follow-up questions.
