### ISSUE TITLE
Problem with geodesic distance method (GOF)

### ISSUE THREAD

**Issue by ureber** [leifeld/btergm#20]
Hello,

I encounter a problem with the geodesic distance method in the GOF function. During the calculation process, I get the following message:

```
Processing statistic: Geodesic distances
  Skipping statistic for the following reason: Error in `.rowNamesDF<-`(x, value = value): duplicate 'row.names' are not allowed
```

I am not sure if this is a data problem or a bug. The only data problem I could think of are duplicate vertex names. However, I checked my data and found only unique vertex names. But what is then causing the error message?

All other methods work fine.

Thank you and best regards,
Ueli

**Comment by leifeld** [comment]
Yes, this is usually indicative of duplicate vertex names, either in the row labels or the column labels, at one of the time points, in one of the objects. If you can't find the problem, you could post a minimal self-contained example, and I could try to track the problem down.

**Comment by ureber** [comment]
I checked and couldn't find any duplicates. Unfortunately, I cannot share my data at this point. I'll see if I can replicate the error with other data. If this is the case, I'll reopen the issue. Thanks.

**Comment by leifeld** [comment]
OK. If you encounter this again with any data you can share, perhaps a smaller, anonymized excerpt of the data, you can also send them directly to me by email.
