### ISSUE TITLE
A new temporal dependency term

### ISSUE THREAD

**Issue by rwss2021** [leifeld/btergm#27]
Hi there! I think your work could be very useful to my current research. And I have a general question on creating temporal dependencies. If I want to use the attached dependency, do I need to create a customized one by myself? If so, could u please provide some suggestions on reading your codes?
<img width="523" alt="Popularity" src="https://user-images.githubusercontent.com/89196466/130244319-e7363360-31f8-42ec-bd0e-f73462f17713.png">
Thank you for your time!

**Comment by leifeld** [comment]
Hi there. Dyadic temporal statistics like delayed reciprocity, memory terms etc., and also the term above, have the advantage that at time `t` the previous networks at `t-1` and before are already known and functions of it can be employed simply as dyadic covariates. To do what you are describing, I would create a list of change statistic matrices and simply add it to the model using an `edgecov` term. Make sure the row and column names of the matrices in the list reference the nodes properly, then the package will automatically take care of any node composition change. Figuring out these change statistics can be tricky, but you could take a look at my [JSS paper](http://dx.doi.org/10.18637/jss.v083.i06) for some examples on delayed reciprocity and memory terms for guidance.

The package does not currently permit writing your own extensions in a comfortable way. In fact, the current temporal statistics are hardcoded in a somewhat crude way by parsing the model formula using regular expressions. See [here](https://github.com/leifeld/btergm/blob/13bcc4ed8b24fc43fd34d0c98b3bddb4f164c844/R/tergmprepare.R#L238) and [here](https://github.com/leifeld/btergm/blob/13bcc4ed8b24fc43fd34d0c98b3bddb4f164c844/R/tergmprepare.R#L291) (and the following lines there) for examples. You will probably not want to do this, but if you decide to hardcode any statistics, please feel free to open a pull request.

The above solution assumes that it does not matter what any dyad other than (kj) does at time `t`, i.e., the dyads are conditionally independent given the other model terms and the past networks, which have already happened. If you think that (ij) must still exist at `t` or that (ik) and (ki) must still be absent at `t` for your statistic to work, then you would need a dyad dependence term. Unfortunately, the way the package was written does not currently permit implementing such temporal endogenous network statistics that involve multiple dyads at `t` as well as past network dyads. So it depends on the assumptions you are willing to make...

**Comment by rwss2021** [comment]
Thanks a lot!!
