### ISSUE TITLE
"xsparse" not found

### ISSUE THREAD

**Issue by haocharliezhang** [leifeld/btergm#36]
Dear btergm team!

Thanks so much for writing this great package!

I have been trying to replicate my previous analysis recently, but " btergm" cannot run on the same data anymore. I have also tried on different machines and found the same issue. The error message is:

Starting pseudolikelihood estimation with 1000 bootstrapping replications using parallel processing on 4 cores...
Error in boot(unique.time.steps, estimate, R = R, Yi = Y, xsparsei = xsparse,  : 
  object 'xsparse' not found
In addition: Warning messages:
1: In btergm(list(ptanet2006, ptanet2007, ptanet2008, ptanet2009, ptanet2010,  :
  The 'speedglm' package was not found. Using the 'glm' function.
2: glm.fit: fitted probabilities numerically 0 or 1 occurred 
3: glm.fit: fitted probabilities numerically 0 or 1 occurred 

Do you know what is going on? I am also happy to send over the data. Thank you very much in advance!

Best,
Hao

**Comment by leifeld** [comment]
Hi Hao! I haven't encountered this before. I'm happy to look into it next week if you could provide a self-contained minimal example. Please send the script and data to my Manchester email address, which you can find under "Contact" on my personal homepage. Before you do so, have you considered installing the speedglm package? And have you considered switching off parallel processing? And could you post the version of your btergm installation here as well as the version of the ergm package installed on your system? Many thanks.

**Comment by haocharliezhang** [comment]
Thanks so much for your prompt reply!!! Everything works after installing speedglm!

**Comment by leifeld** [comment]
I'm glad it's been resolved. But it still should have worked without speedglm.

Have you also considered installing fastglm? That should speed up the computations even more than speedglm.
