### ISSUE TITLE
xquarz dependence for mac osx users

### ISSUE THREAD

**Issue by brandenberger** [leifeld/btergm#5]
Noticed that you need to have xquarz (x11) installed for the btergm-package to load. 
Adding this issue based on @leifeld's request.

I'll attach a screenshot once I've reproduced the error-message on a mac without xquarz (probably my wife's, so it'll have to wait until I'm back in Bern).

**Comment by leifeld** [comment]
> library("btergm")
Fehler: package or namespace load failed for ‘btergm’:
 .onLoad in loadNamespace() für 'tcltk' fehlgeschlagen, Details:
  Aufruf: fun(libname, pkgname)
  Fehler: X11 library is missing: install XQuartz from xquartz.macosforge.org

**Comment by leifeld** [comment]
I have no way of diagnosing MacOS problems. If somebody has the same problem and has any idea what to do about it, please let me know. I will close this issue for now.
