### ISSUE TITLE
data helper functions

### ISSUE THREAD

**Issue by vincentarelbundock** [leifeld/btergm#6]
Hi,

One of the pain points that I've encountered when using `btergm` is converting panel data from its more common representations to objects on which we can run the network analysis.

I wrote a few helper functions with lots of sanity checks. Not sure if this would be of any interest to the community, but I thought I would post it here in case someone has comments or suggestions. There's an example in the README.

Cheers!

https://github.com/vincentarelbundock/btergmHelper

**Comment by leifeld** [comment]
Thanks! I'll close this as there are no follow-up posts.
