### ISSUE TITLE
`btergm` uses a number of deprecated or replaced functions in `ergm`

### ISSUE THREAD

**Issue by krivit** [leifeld/btergm#9]
Moved to `statnet.common`:
* `sweep.mcmc.list`
* `colMeans.mcmc.list`

No longer exported as functions but are registered as methods:
* `simulate.formula`

Also, `btergm()` is never tested with `offset!=FALSE`, and there are a number of issues there.

There may be others.

**Comment by leifeld** [comment]
Hi Pavel! Thanks for the note (and also the e-mail). I believe I have fixed all dependencies, and I have added some unit tests, including `offset = TRUE` and other options. But please let me know in case you see any problems. Thanks.

**Comment by krivit** [comment]
Philip @leifeld , could you please release the current `master` to CRAN? It's compatible with the `ergm` that's on CRAN now, as far as I can tell, and it'll make updating `ergm` easier. Thanks in advance.

**Comment by leifeld** [comment]
@krivit I have submitted it to CRAN, but they are holding it back until you have submitted new versions of `ergm` and `statnet.common` to CRAN as well. They would like to process the packages together. Can you please send a note to Kurt Hornik once you are submitting your packages? He is aware of the situation and suggested this route. Thx!
